"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is
minimised; what is the value of D?
"""

from math import sqrt


def P(n):
    return n * (3 * n - 1) / 2


def is_pentagonal(x):
    c = -(2 * x)
    n = (1 + sqrt(1 - 12 * c)) / 6

    return True if n.is_integer() else False


pentagonal_list = [1]
i = 1
not_found = True


while not_found:
    i += 1
    pentagonal_list.append(P(i))

    for current_pentagonal in pentagonal_list:
        if pentagonal_list[-1] - current_pentagonal in pentagonal_list:
            if is_pentagonal(pentagonal_list[-1] + current_pentagonal):
                print(abs(pentagonal_list[-1] - current_pentagonal))
                not_found = False
