"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def P(n):
    return int(n * (3 * n - 1) / 2)


def H(n):
    return n * (2 * n - 1)


def PH(n):
    Pn = 1
    Hn = 1
    index = 0

    while index != n:
        if P(Pn) == H(Hn):
            index += 1
            Hn += 1

        while H(Hn) != P(Pn):
            if H(Hn) > P(Pn):
                Pn += 1

            else:
                Hn += 1

    return H(Hn)


print(PH(2))
