"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""

sum_of_evens = 0
a = 1
b = 1
c = a + b

while c < 4000000:
    sum_of_evens += c
    a = b + c
    b = a + c
    c = a + b

print(sum_of_evens)
